### ISSUE TITLE
issue with php 7.3+

### ISSUE THREAD

**Issue by preciouscoder** [guzzle/promises#100]
Get error in php 7.3.1

PHP Parse error: syntax error, unexpected '[', expecting ')' in guzzlehttp/promises/src/functions.php on line 45

**Comment by pjeby** [comment]
I think you have mistaken PHP 5.3.1 for PHP 7.3.1.  See [this eval](https://3v4l.org/KRbfC), which shows the error you are describing for PHP 5.3.0-5.3.29, but not for any version from 5.4 up.  You are probably trying to run with the wrong PHP interpreter.

**Comment by Tobion** [comment]
As explained by @pjeby, you are using an outdated php version that is not supported anymore. See composer requirements.
