### ISSUE TITLE
Add splat() function

### ISSUE THREAD

**Issue by shadowhand** [guzzle/promises#11]
I was just writing some code that would have been greatly improved by having a `splat()` function that works similarly to `all()`.

The current code is:

``` php
Promise\all($promises)->then(function ($results) {
    list($first, $second) = $results;
    ...
});
```

But what I would rather write is:

``` php
Promise\splat($promises)->then(function ($first, $second) {
    ...
});
```

This would require PHP >= 5.6 for [argument unpacking](https://wiki.php.net/rfc/argument_unpacking) or the use of `call_user_func_array`.

**Comment by kelunik** [comment]
There's no reason to have another `then()` there, just `Promise\splat($promises, function ($first, $second) { ... })` should be enough.

**Comment by GrahamCampbell** [comment]
I don't feel that this is necessary.
