### ISSUE TITLE
Exceptions in nested handlers are not reported

### ISSUE THREAD

**Issue by shadowhand** [guzzle/promises#12]
```php
$p = new Promise();
$p->then(function () {
    $inner = new Promise();
    $inner->then(function () {
        throw new \RuntimeException('This exception should not be trapped');
    });
    $inner->resolve(true);
    $inner->wait();

    print_r(['state' => $inner->getState()]);

    return $inner;
});
$p->resolve(true);
$p->wait();

print_r(['state' => $inner->getState()]);
```

In this scenario, the `RuntimeException` should not be trapped. Both promises are **correctly** fulfilled but the exception is never seen.

## Expected Result

1. `RuntimeException` is thrown.

## Current Result

1. `RuntimeException` is never seen.

**Comment by jeskew** [comment]
A promise is meant to encapsulate success and failure, the latter case often being represented as an exception. This is part of the [A+ spec](https://promisesaplus.com/#point-62).

You can [unwrap a promise by calling `wait`](https://github.com/guzzle/promises#synchronous-wait), which will throw any exceptions contained in the promise. Exceptions will also be passed to your [`onRejected` handler](https://github.com/guzzle/promises#api).

**Comment by shadowhand** [comment]
@jeskew updated my test case to include `wait` calls. No change.

**Comment by mtdowling** [comment]
In your example, you're waiting on the promise that was resolved. The promise that has the exception thrown and is rejected is actually a different promise that is returned by the `then` method of the resolved promise.  You'll need to wait on the dependent promise in order to be affected by it's error when waiting. Something like this:

```php
$p1 = new Promise();
$p2 = $p1->then(function () {
    $inner = new Promise();
    $inner->then(function () {
        throw new \RuntimeException('This exception should not be trapped');
    });
    $inner->resolve(true);
    $inner->wait();

    print_r(['state' => $inner->getState()]);

    return $inner;
});
$p1->resolve(true);
$p2->wait();
```

**Comment by shadowhand** [comment]
@mtdowling the code you provided still swallows the exception completely and no promises are rejected. While this scenario could be interpreted under [2.3.3.3.4.1](https://promisesaplus.com/#point-61) it is not actually the same, because no promises are every rejected with the current test case.

The bottom line is that completely trapping an exception in a way that it **cannot be seen** is a huge problem. In this test scenario, the exception will never appear and all promises are fulfilled. The exception is not captured as a rejection reason and effective disappears into nothingness.

**Comment by shadowhand** [comment]
Oops, wrong button.

**Comment by mtdowling** [comment]
Looking deeper into the example, you're making the same mistake in your inner promise -- you're waiting on the promise that is fulfilled successfully rather than waiting on the promise created with the `then` function that is rejected by the exception. We should definitely not throw that exception because it wouldn't be following the promises spec.

**Comment by shadowhand** [comment]
Okay, so my test scenario should look like:

```php
$p1 = new Promise();
$p2 = $p1->then(function () {
    $p3 = new Promise();
    $p4 = $p3->then(function () {
        throw new \RuntimeException('This exception should not be trapped');
    });

    $p3->resolve(true);

    return $p4;
});
$p1->resolve(true);
$p2->wait();
```

Which does correctly trigger the exception. My brain hurts.

**Comment by mtdowling** [comment]
Ah yes, that looks better.

**Comment by shadowhand** [comment]
@mtdowling the problem was the my code needed to be able to collect all of the promises (and promises created by those promises) and unwrap them all at once. My solution is [ProxyPromise](https://gist.github.com/shadowhand/c0cb6ea03767e31827f7).
