### ISSUE TITLE
Grammatical errors

### ISSUE THREAD

**Issue by RealWorldEdits376W** [guzzle/promises#149]
In the Callbacks section, there are grammatical errors, in the last paragraph, which is just below the code snippet.
The sentence is written as, "Resolving a promise means that you either fulfill a promise with a value or reject a promise with a reason. Resolving a promises triggers callbacks registered with the promises's then method."

The corrected sentence could be written as, "Resolving a promise means that you either fulfill a promise with a value or reject a promise with a reason. Resolving a **promise** triggers callbacks registered with the **promises'** then method. 

Thank you.

**Comment by GrahamCampbell** [comment]
Fixed, thanks.
