### ISSUE TITLE
More extensible Promises

### ISSUE THREAD

**Issue by berarma** [guzzle/promises#15]
Hi.

I'm thinking about different ways to use Promise objects and I just noticed I wouldn't be able to extend the Promise object without rewriting some code.

Maybe using *static::class* instead of the literal class name in https://github.com/guzzle/promises/blob/master/src/Promise.php#L35 is all that would be needed.

It's not a real issue right now, just sharing this idea.
Cheers.

**Comment by mtdowling** [comment]
That would assume that subclasses have the same constructor signature, which is not a requirement or a part of LSP. I also would discourage you from extending Promise -- treat it as a built-in data structure type. A better approach, if necessary, is to decorate the promise.

**Comment by berarma** [comment]
Certainly, that's the right way to do it. I didn't realize at first. Thanks!
