### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by joshdifabio** [guzzle/promises#23]
Please tag a new release so that there's a stable version with `Throwable` support.

**Comment by joshdifabio** [comment]
The lack of a tag with `Throwable` support is beginning to make things difficult for me. Is there any plan to tag master any time soon? @mtdowling

**Comment by mtdowling** [comment]
Sorry for the wait. 1.2.0 is tagged and released.

**Comment by joshdifabio** [comment]
Thanks!
