### ISSUE TITLE
Error in the documentation

### ISSUE THREAD

**Issue by castarco** [guzzle/promises#25]
Hello,

there is an error in the documentation. The last piece of shown code refers to the `deliver` method, but this method does not exist in the whole Promises code base:

```php
$promise = new Promise();
$promise->then(function ($value) { echo $value; });
// The promise is the deferred value, so you can deliver a value to it.
$promise->deliver('foo');
```

This code is broken because the `deliver` method is not defined, and will throw a PHP fatal error, but we can find this example in the documentation.

**Comment by jeskew** [comment]
Thanks for reporting! That should be `$promise->resolve('foo')`; I'll open a PR to correct the docs.
