### ISSUE TITLE
Using "then" for determining whether an argument is a promise.

### ISSUE THREAD

**Issue by aronbeal** [guzzle/promises#31]
Hi,

I'd just like to make a request about this bit of code in FulfilledPromise:

```php
        if (method_exists($value, 'then')) {
            throw new \InvalidArgumentException(
                'You cannot create a FulfilledPromise with a promise.');
        }
```

Is there *any* chance you could change that first line to:

```php
      if ($value instanceof 'GuzzleHttp\Promise\PromiseInterface')){
```

I'm trying to pass a non-promise object as an argument, and it's bailing because my object has a 'then' method.

**Comment by aronbeal** [comment]
(this of course applies to RejectedPromise as well)

**Comment by mtdowling** [comment]
Sorry, removing that feature would be a breaking change for anyone who is using Guzzle promises to interop with other promise libraries. This could be updated eventually if a Promise interface is standardized (like with a PSR), but until then, I can't remove it.

**Comment by aronbeal** [comment]
Ok, so be it.  Thanks for considering.
