### ISSUE TITLE
How to return resolved promises in a list when one fails in `all` function

### ISSUE THREAD

**Issue by byrnedo** [guzzle/promises#40]
I have a list of promises where I want to get the results of those that managed to succeed even when one  or more fails. Can I do this with `all`?

**Comment by jeskew** [comment]
Hi @byrnedo,

You can get the results of an array of promises without converting any failures into thrown exceptions by using [`inspect_all`](https://github.com/guzzle/promises/blob/master/src/functions.php#L174) instead of `all`.

**Comment by byrnedo** [comment]
Great, thanks ! :)
