### ISSUE TITLE
Done instead of Then

### ISSUE THREAD

**Issue by socketman2016** [guzzle/promises#41]
Please see https://github.com/reactphp/promise#done-vs-then
How can I have "done" in guzzle/promises?

I need this feature in Event Loop Integration

> Calling done() transfers all responsibility for errors to your code. If an error (either a thrown exception or returned rejection) escapes the $onFulfilled or $onRejected callbacks you provide to done, it will be rethrown in an uncatchable way causing a fatal error.

**Comment by sagikazarmark** [comment]
Moving to #44
