### ISSUE TITLE
Unwrapping a promise in Event Loop Integration

### ISSUE THREAD

**Issue by sm2017** [guzzle/promises#42]
How can I unwrap a promise when integrated with Event Loop?

**Comment by mtdowling** [comment]
If you're using an event loop, then you don't need to unwrap or wait on a promise. Instead, you should use promise callbacks to receive the result of a promise.

The only way to unwrap a promise is to call wait on it. This could have consequences in an event loop based application in that waiting could cause a promise fulfilled with a promise to block on that  promise to complete before returning a value.
