### ISSUE TITLE
 reactphp/promise

### ISSUE THREAD

**Issue by sm2017** [guzzle/promises#43]
How can I convert guzzle/promises to reactphp/promise ?

``` php

// $guzzlePromise is an instance of GuzzleHttp\Promise\Promise and is a result of third party library
$reactPromise = convert($guzzlePromise);
```

**Comment by sagikazarmark** [comment]
In HTTPlug we have a custom promise interface for async HTTP clients and we also provide an adapter for Guzzle 6, so we did the following:

https://github.com/php-http/guzzle6-adapter/blob/master/src/Promise.php

Hope that helps

**Comment by mtdowling** [comment]
Yeah, something like that would work. You just need to create a deferred that is resolved or rejected once the Guzzle promise is resolved or rejected.
