### ISSUE TITLE
Changeable TaskQueue for better event loop integration

### ISSUE THREAD

**Issue by alexeyshockov** [guzzle/promises#49]
I would like to propose a change for better event loop integration.

**The issues**

Current way for event loop integration (using `addPeriodicTimer` or `futureTick`) leads to 100% CPU load, because it kills the whole idea. There is always something to do (run the promises queue), so the timeout before the next tick is always 0 or near it.

It also leads to an endless event loop, because, again, there is always something to do.

**The proposed solution**

Make the TaskQueue changeable in the code, to be able to set a proper implementation in case of an event loop. A simple event loop implementation could do `$loop->nextTick([$queue, 'run'])` inside the `add()` method, so only when it's needed.

I think it can be done with

1. introducing `TaskQueueInterface` that will contain all methods from the current `TaskQueue`,
2. adding `TaskQueue::getInstance()` and `TaskQueue::setInstance(TaskQueueInterface $q)` methods,
3. changing calls to `queue()` inside the code to `TaskQueue::getInstance()`.

This way doesn't require BC breaks.

What do you think about it?

**Comment by joshdifabio** [comment]
This functionality is already in master, it just needs to be tagged.

**Comment by alexeyshockov** [comment]
@joshdifabio, you made me feel stupid :) Haven't checked the code from master, only the doc (that is not updated).

Waiting for #48 then.
