### ISSUE TITLE
Omit the parameter in the callback function of then/otherwise

### ISSUE THREAD

**Issue by tzfrs** [guzzle/promises#53]
This is not an issue, I just wanted to get your opinion on a topic.

To resolve a promise we do

`$promise->then(function[...]`

The callback parameter gets the `ResponseInterface $response`  as function parameter. What if I don't want to use that value? If I just want to log something, or dunno, do something else which has nothing to do with the response. Do you think it's good practice to do `$promise->then(function ()` or would you always write `$promise->then(function (ResponseInterface $response))` even though you won't need that parameter?

Was just wondering, because omitting the parameter would mean, that we are getting a warning about calling a method with no parameter, right?

**Comment by joshdifabio** [comment]
> Was just wondering, because omitting the parameter would mean, that we are getting a warning about calling a method with no parameter, right?

You can omit the parameter from your closure; PHP won't raise a warning.

**Comment by tzfrs** [comment]
Will there not be thrown a warning because I'm using a closure or is there a different reason?

**Comment by jeremeamia** [comment]
You can pass whatever arguments you want to a function (as long as it doesn't conflict with any declared parameters), but the function doesn't necessarily have to acknowledge them. This has been the foundation of variadics prior to PHP 5.6. See https://3v4l.org/UMmpV
