### ISSUE TITLE
How promise is async

### ISSUE THREAD

**Issue by saikatdutta1991** [guzzle/promises#65]
It runs promise callbacks on php script shutdown.. So all the promises will be executed one by one..

i want to know if it really works parallel

**Comment by mtdowling** [comment]
It depends on what you're using to fulfill promises and whether or not it will execute them concurrently. For example, if your promises are all using something like Guzzle with a cURL based handler, then your promises will be resolved concurrently (note that Guzzle doesn't use threads to resolve promises, so they are resolved concurrently and not in parallel).

**Comment by saikatdutta1991** [comment]
thanks...thanks alot.
