### ISSUE TITLE
Can I manipulate the response body on fulfilled promise with a callback?

### ISSUE THREAD

**Issue by arderyp** [guzzle/promises#66]
here's my example:

```
// Build Asynchronous Promise
$promise = $this->client->requestAsync($this->method, $path, $options);

// Extract target data from response JSON after request fulfilled
$promise->then(
    function ($response) {
        $result = GuzzleResponseParser::parse($response);
        $extracted = $this->getTargetDataFromResult($result);

        //This dumps the right data
        //var_dump($extracted);
        //exit();

        // This, however, does not work as I'd expect.  It doesn't error, but see notes below.                 
        return $extracted;
    }
);
```

I am later using

```
$results = Promise\unwrap($promises);
foreach ($results as $key => $result) {
    $this->data[$key] = $result;
}
```

I was hoping the `$extracted` in the `then()` closure would translate to the `$result` in the post-unwrap loop, but this does not happen.  I see the regular result, not the extracted result.

Am I going about this wrong?  I've reviewed documentation and can't seem to find what I need.  Might the be another way to do this, or is it not possible?  Thanks in advance!

**Comment by sagikazarmark** [comment]
In theory, this should work. Note that `->then` returns a new promise object.

**Comment by arderyp** [comment]
Hmm, is there any further testing you could suggest I do?  My `$extracted` object is _not_ a promise, but a standard php object representation of a subsection of the response's json.  Thanks for the help.

**Comment by sagikazarmark** [comment]
The parameter of then is a callback which indeed returns whatever you want it to return. The then call on the other hand returns a Promise, which will call your passed callback upon resolution.

**Comment by sagikazarmark** [comment]
Try this code:

``` php
// Build Asynchronous Promise
$promise = $this->client->requestAsync($this->method, $path, $options)->then(
    function ($response) {
        $result = GuzzleResponseParser::parse($response);
        $extracted = $this->getTargetDataFromResult($result);

        //This dumps the right data
        //var_dump($extracted);
        //exit();

        // This, however, does not work as I'd expect.  It doesn't error, but see notes below.                 
        return $extracted;
    }
);
```

**Comment by arderyp** [comment]
That worked!  My question now is, why?  How is it different than what I was trying earlier?  Does calling the `then()` function on the promise variable explicitly work differently (or not work) as opposed to using it in a chain approach, as demonstrated in your answer?  I wouldn't think this would make a difference, but maybe I;m misunderstanding something.

**Comment by jeskew** [comment]
Calling `then` returns a new promise. The original promise is unchanged, as is its return value.

**Comment by sagikazarmark** [comment]
You might want to read about Promises in general as it is not invented by Guzzle.

**Comment by arderyp** [comment]
@jeskew, I'm not sure your response explain why defining the promise to a variable and calling then() on said $promise variable yields different results than calling the same method with the same arguments via chaining.  But alas, it is working nonetheless. I'll look into Promises in general @sagikazarmark to see if there may be an explanation there. Thanks for the help.

**Comment by sagikazarmark** [comment]
His comment explains the behaviour. Look into Promises to see the reason why.

But I think what you miss here is this:

`$promise = $this->client->requestAsync($this->method, $path, $options)->then(...);

// is the same as

$promise = $this->client->requestAsync($this->method, $path, $options)
$promise = $promise->then(..);
```

Since `then` returns a new promise, you need to resolve the last promise that you called then on. In your code setting the value of the `$promise` variable is missing, that's why it doesn't work.

Again, to understand why then returns a new promise, you should really look into promises in general.

**Comment by arderyp** [comment]
Oh, sorry, I read that too quickly.  That makes total sense now.  THANK YOU!  Sorry @jeskew, thanks for the info.
