### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by BillOTei** [guzzle/promises#67]
I can't seem to find a "core" answer that is really important to me, sorry if obvious/written but how does a core promise object can work async? Does it pops a new php process on the server or separate thread?
Thks for the hints.

**Comment by mtdowling** [comment]
No threads or processes are spawned. All the work happens in a single, non-blocking thread of execution.

How promise resolution works with this library really depends on how you are using it. If you are using this library with Guzzle and the cURL handlers, then what you really get is a way to multiplex sockets efficiently and create pipelined workflows using promises.

If you hook something like Guzzle up to React or another non-blocking I/O framework, then promise resolution occurs when their event loop is ticked.
