### ISSUE TITLE
Asynchronous sleep

### ISSUE THREAD

**Issue by sminnee** [guzzle/promises#71]
I was building some async code that triggers a delayed retry in the case of an error, similar to:

```php
$promise = $client->getAsync(...);

$promise->then(
  function ($result) { ... },
  function ($error) {
    sleep(5); 
    $client->getAsync(...);
  }
);
```

Of course, `sleep(5)` is blocking. Is there an asynchronous equivalent for sleep, such as a promise that will resolve within a `wait()` call after the given amount of time? If not, can one be added to the library?

**Comment by alexeyshockov** [comment]
There is no concurrent version of `sleep()` in Guzzle Promises out of the box. You can take a look at [a library](https://github.com/productsupcom/guzzle-react-bridge) (I'm the developer) which integrates Guzzle with [React PHP](http://reactphp.org/). With React you can use timers to create "sleep promises" (see [`sleep_fn`](https://github.com/productsupcom/guzzle-react-bridge/blob/master/src/functions.php#L88)).

But if you need just delayed retries, try to use [the default retry middleware](https://github.com/guzzle/guzzle/blob/master/tests/RetryMiddlewareTest.php). Also [a usage example](https://github.com/addwiki/mediawiki-api-base/blob/49512c3a17b3a94c74c0f210486eefd37eb7549d/src/Guzzle/MiddlewareFactory.php#L57).

**Comment by mtdowling** [comment]
Guzzle (the client) also supports the `delay` request option which can be used to delay the sending of a request: http://docs.guzzlephp.org/en/stable/request-options.html#delay.

**Comment by sminnee** [comment]
Thanks for the advice. I'll check out the React bridge.

The default retry middleware, uses the Guzzle delay option, which uses a `usleep() call. My understanding is that this would block other requests from being processed in the meantime.

My use-case is a domain scanner, so efficient parallel processing is quite important for its overall performance.

**Comment by mtdowling** [comment]
Only the blocking handlers use usleep. The [CurlMultiHandler](https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlMultiHandler.php) does not.

**Comment by abiusx** [comment]
You can use GuzzleHttp to send a request to a non-existing server with a certain delay. This can work as an async sleep.

**Comment by elcreator** [comment]
> Only the blocking handlers use usleep. The [CurlMultiHandler](https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlMultiHandler.php) does not.

CurlMultiHandler uses usleep too: https://github.com/guzzle/guzzle/blob/7.8/src/Handler/CurlMultiHandler.php#L187
