### ISSUE TITLE
<b>Fatal error</b>:  Interface 'GuzzleHttp\Promise\TaskQueueInterface' not found in

### ISSUE THREAD

**Issue by mirzazeyrek** [guzzle/promises#72]
Fatal error:  Interface 'GuzzleHttp\Promise\TaskQueueInterface' not found in <b>vendor/guzzlehttp/promises/src/TaskQueue.php</b> on line
>13

Can someone explain how this can be solved ?

**Comment by alexeyshockov** [comment]
Does reinstall help? The interface is there, and it works for me. Try to remove `vendor/` and run `composer install` on a "fresh" project.

**Comment by Nyholm** [comment]
If not reinstall helped, can you give us some versions of what you are using?

`composer show | grep guzzle`

**Comment by mirzazeyrek** [comment]
Hello Nyholm,

This is the output of the command:

![image](https://user-images.githubusercontent.com/6233650/28465728-76ff213e-6e32-11e7-8fd7-1eb5b3bace69.png)

**Comment by mirzazeyrek** [comment]
Here is the composer.json file:

![image](https://user-images.githubusercontent.com/6233650/28465790-b84e0434-6e32-11e7-85d7-705a7f48e69c.png)

**Comment by Nyholm** [comment]
You must use composers autoloader. Require vendor/autoload.php and you will be fine.

**Comment by dilawar** [comment]
For me this https://stackoverflow.com/a/41057022/1805129 fixed it. Most likely a bug in version v1.3.1 .
I had `require_once 'vendor/autoload.php'` .

```
guzzlehttp/guzzle            6.2.2  Guzzle is a PHP HTTP client library
guzzlehttp/promises          v1.3.1 Guzzle promises library
guzzlehttp/psr7              1.3.1  PSR-7 message implementation
```

**Comment by sagikazarmark** [comment]
Nope, just checked and it's fine. Do you install things from source or from dist packages? If from source: can you check the ref checked out?

**Comment by dilawar** [comment]
I use `composer`. There is no sign of `.git` or `.svn` etc in installation. `composer.json` is following.

```
{
    "name": "guzzlehttp/promises",
    "description": "Guzzle promises library",
    "keywords": ["promise"],
    "license": "MIT",
    "authors": [
        {
            "name": "Michael Dowling",
            "email": "mtdowling@gmail.com",
            "homepage": "https://github.com/mtdowling"
        }
    ],
    "require": {
        "php": ">=5.5.0"
    },
    "require-dev": {
        "phpunit/phpunit": "^4.0"
    },
    "autoload": {
        "psr-4": {
            "GuzzleHttp\\Promise\\": "src/"
        },
        "files": ["src/functions_include.php"]
    },
    "scripts": {
        "test": "vendor/bin/phpunit",
        "test-ci": "vendor/bin/phpunit --coverage-text"
    },
    "extra": {
        "branch-alias": {
            "dev-master": "1.4-dev"
        }
    }
}
```

**Comment by sagikazarmark** [comment]
Can you check what's at `ls $HOME/.composer/cache/files/guzzlehttp/promises/`

**Comment by sagikazarmark** [comment]
Can you please unzip the content and paste the result here?

```bash
$ unzip ba05e5df3bded4f01482d4b16ae313a79742eba6.zip
$ cat guzzle-promises-a59da6c/src/TaskQueue.php | grep "class TaskQueue"
```

**Comment by dilawar** [comment]
```
-bash-4.1$ cat guzzle-promises-a59da6c/src/TaskQueue.php | grep 'class TaskQueue'
class TaskQueue implements TaskQueueInterface
-bash-4.1$ 
```

**Comment by sagikazarmark** [comment]
Well, it looks like the composer package includes the correct version and it includes the interface implementation. I don't really see how this can be a Guzzle issue. I can imagine some cache/vendor issue on your side, but I don't know what it can be.

Have you tried deleting the vendor directory and running composer install as suggested above?

**Comment by dilawar** [comment]
Well there is something fishy in `composer.lock`. Not sure how to interpret this.

``` 
 265              "require-dev": {                                                     
 266                 "friendsofphp/php-cs-fixer": "^1.11",                            
 267                 "guzzlehttp/promises": "0.1.1|^1.3",                             
 268                 "phpunit/phpunit": "^4.8.36",                                    
 269                 "sebastian/comparator": ">=1.2.3"                                
 270             },

 304             "require": {                                                         
 305                 "guzzlehttp/promises": "^1.0",                                   
 306                 "guzzlehttp/psr7": "^1.3.1",                                     
 307                 "php": ">=5.5"                                                   
 308             }, 
 352         {                                                                        
 353             "name": "guzzlehttp/promises",                                       
 354             "version": "v1.3.1",                                                 
 355             "source": {                                                          
 356                 "type": "git",                                                   
 357                 "url": "https://github.com/guzzle/promises.git",                 
 358                 "reference": "a59da6cf61d80060647ff4d3eb2c03a2bc694646"          
 359             },
````
Seems like there are multiple version of promise `"guzzlehttp/promises": "0.1.1|^1.3"` and `"guzzlehttp/promises": "^1.0", ` and version `1.3.1` are there. Do you think its fine.

Again, I faced this break when migrating to `php7` from `php5`.

**Comment by sagikazarmark** [comment]
The lock seems to be fine, at least the commit hash and the version seems to be ok. 

You could also check the installed.json file, it tells you the currently installed version. If that is fine too, I'm out of ideas. The cached version is correct, the lock is correct, something went wrong during installation.

**Comment by loopy3025** [comment]
This seems problematic...

![image](https://user-images.githubusercontent.com/6729935/49663445-ad666f80-fa1c-11e8-9c39-daf9493fbe8e.png)
