### ISSUE TITLE
Any any/all/race/some functions are provided?

### ISSUE THREAD

**Issue by shtse8** [guzzle/promises#75]
I am switching to Guzzle Promise from React Promise. But I don't know how to do it in Guzzle if I want to wait all promised to be resolved.

**Comment by alexeyshockov** [comment]
There are mostly the same functions `all()`, `any()` and `some()` in [functions.php](https://github.com/guzzle/promises/blob/master/src/functions.php#L307). Take a look at other functions too, each one is annotated with a description.

P.S. Also you can vote for a PR (#70) with the same functions but with concurrency control ;)

**Comment by shtse8** [comment]
Thanks for your help. Let me try.

**Comment by RinkAttendant6** [comment]
Can these be documented in the README or at least mentioned? The only one I see is `queue`
Or if there's some other documentation elsewhere then a link would be nice.
