### ISSUE TITLE
Throwing Exception from within promises handler doesn't stop script execution

### ISSUE THREAD

**Issue by dareenzo** [guzzle/promises#78]
I'm doing some integration testing with a library and use guzzle to make an async http request and noticed that my tests were always passing even when that is not expected. Through debugging narrowed down the issue to being caused by the fact that an exception thrown from a `then` in a promise won't stop the system from running.

In the snippet bellow for instance, I'm able to get the log in the error.log but PHPUnit never gets the exception when running the unit test. I also tried running this in isolation outside of the unit testing context and same behavior is exhibited

```php
$promise = $httpClient->requestAsync('GET', 'http://some-api-url');

$promise->then(
    function ($response) {
        error_log('Exceptions thrown in promise do not bubble-up');
        throw new Exception('Invalid hit sent. got response: ' . $response->getBody());
    },
    function ($exception) {
        // handle HTTP request exception
    }
);
```

Is this behavior expected? Am I doing something wrong?

Thanks

**Comment by alexeyshockov** [comment]
If this is the complete code, then the behaviour is valid. You have to call `->wait()` on a promise to process the callback (task) queue. Or use some aggregation functions like [`all()`](https://github.com/guzzle/promises/blob/master/src/functions.php#L220).

**Comment by dareenzo** [comment]
I do call `->wait()` after this bit to ensure the promise is processed. And it does get processed as later on I'm able to see the log message. My problem is that the exception does not bubble up, and thus I cannot know if there was an exception thrown or not.

Is it like within the task queue there's some sort of global error trapper?

**Comment by jsor** [comment]
Exceptions thrown in fulfillment callbacks reject the promise **returned** from `then()`. You must call `wait()` on the returnd promise.

```php
$newPromise = $promise->then(
    function ($response) {
        throw new Exception('Invalid hit sent. got response: ' . $response->getBody());
    }
);

$newPromise->wait();
```

**Comment by dareenzo** [comment]
Probably I could clarify my issue with the sample bellow.

I have phpunit installed globally and guzzle installed as a library

```php

require 'vendor/autoload.php';

use GuzzleHttp\Client;

class GuzzlePromisesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * The http client
     * @var GuzzleHttp\ClientInterface
     */
    protected $httpClient;

    public function setUp() {
        $this->httpClient = new Client();
    }

    /**
     * @test
     * @expectedException Exception
     */
    public function should_trap_thrown_exception() {
        $promise = $this->httpClient->requestAsync('GET', 'https://www.google-analytics.com/debug/collect?v=1&aip=1&tid=UA-0000-00');

        $promise->then(
            function ($response){
                throw new Exception('Invalid hit sent. got response: ' . $response->getBody());
            }
        );

        $promise->wait();
    }
}
```

```log
➜  tracking git:(use-guzzle-for-async-http-reqs) ✗ phpunit ~/Desktop/files/file.php
PHPUnit 5.1.3 by Sebastian Bergmann and contributors.

F                                                                   1 / 1 (100%)

Time: 1.69 seconds, Memory: 10.00Mb

There was 1 failure:

1) GuzzlePromisesTest::should_trap_thrown_exception
Failed asserting that exception of type "Exception" is thrown.

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

Note that if you navigate to the URL used in the test, you'll get a JSON response stating there are errors in the request data, but please mind the status code is 200. Meaning no "error" should be thrown by guzzle regarding the request. 

However an error should be thrown from the promise handling. And that is what I expect to trap of the test

Thanks

**Comment by jsor** [comment]
That's exactly covered by my comment https://github.com/guzzle/promises/issues/78#issuecomment-332185411 above.

You need to `wait()` on the returned promise.

```php
    public function should_trap_thrown_exception() {
        $promise = $this->httpClient->requestAsync('GET', 'https://www.google-analytics.com/debug/collect?v=1&aip=1&tid=UA-0000-00');

        $newPromise = $promise->then(
            function ($response){
                throw new Exception('Invalid hit sent. got response: ' . $response->getBody());
            }
        );

        $newPromise->wait();
    }
```

**Comment by dareenzo** [comment]
Ohhhh sorry ...  Didn't notice I have to wait on the new promise returned by `then` on the first promise.

Doing as suggested does work.

Thanks
