### ISSUE TITLE
Allow throwing an exception to actually propagate

### ISSUE THREAD

**Issue by SudoPlz** [guzzle/promises#92]
Hey there,

I've got the following code:

```
$promise->then(
                // $onFulfilled
                function ($user) {
                   // bla bla
                },
                // $onRejected
                function ($reason) {
                    throw new Error('reset_password_token_expired');
                }
            );
```

but the error is being caught.

What can I do to allow it to propagate up the error chain and crash the app?

Thank you

**Comment by pjeby** [comment]
If you need to force a crash, you have to `Promise\queue()->add()` a function that throws the error.

**Comment by Tobion** [comment]
If you call `$promise->wait(true)`, your exception should be thrown. See https://github.com/guzzle/promises/blob/ac2529fc650684c5cd687e2b462d046cdbed556e/src/PromiseInterface.php#L81-L82

What's the problem here? Did you forget to actually resolve/wait on the promise?

**Comment by Tobion** [comment]
ping @SudoPlz

**Comment by SudoPlz** [comment]
It's been such a long time, I don't even remember, let's close this.
Thanks for pinging me.
