### ISSUE TITLE
The each() function is deprecated

### ISSUE THREAD

**Issue by alexquantox** [guzzle/promises#93]
PHPUnit throws deprecation error for this, because as from PHP7.2 each() function is deprecated

https://github.com/guzzle/promises/blob/master/src/functions.php#L223

http://php.net/manual/en/function.each.php

**Comment by sayhitovincent** [comment]
Are we able to have this investigated?

**Comment by alexeyshockov** [comment]
@alexquantox, this is call is **not** for `\each()` (PHP's built-in function, deprecated), but for `\GuzzleHttp\Promise\each()` that lives in the same file.

Please, update the ticket with the error that you get from PHPUnit. Also there is [another ticket that can be related](https://github.com/guzzle/guzzle/issues/2174).
